import { Toaster } from "react-hot-toast";
import { reemKufi } from "./font";
import "./globals.css";
export const metadata = {
  title: "OSE Cerfiticate",
  description: "Generated by OMAN GOV",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={reemKufi.className}>
        {children}
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
